version: '3.7'
services:
  web:
    build:
      context: .
    image: johncolby/rad_apps
    secrets:
    - .env
    environment:
      REDIS_URL: redis://redis
      DOTENV_FILE: /run/secrets/.env
    command: gunicorn -b :5000 --access-logfile - --error-logfile - rad_apps:app
    ports:
    - "5001:5000"
    networks:
    - net
  worker:
    image: johncolby/rad_apps
    volumes:
      - $OUTPUT_DIR_HOST:/output_dir
    deploy:
      replicas: 4
    secrets:
    - .env
    environment:
      DOTENV_FILE: /run/secrets/.env
    command: rq worker -u redis://redis
    networks:
    - net
  redis:
    image: redis
    networks:
    - net
networks:
  net:
    attachable: true
secrets:
  .env:
    file: .env